travis:
  secure:
    BINSTAR_TOKEN: ts6mT2qTkXhSByjO0lWZceX6PBS2J0/PyrYcNlFk3GTkL/uYQS6H2yjT3hhodsRoieG2kPscDXjCw4OoGDgplNh1rHv/y0+QL/z6ylkWY9unhOwHP4ALZsWZO7WsoMVjLrNmPjIEJp6C+E8G05HHCq1Fl/3SEozASNk61da6Ug/ccnQpX+pP0rumMOwfhYCN3SXiuCPjHvqr2upHD00ngyuATpzCEZdxNRjqLcfvMvqfsT8vIHwalUf/aoi8Pkkz2GfWgCiXmdgSqHCfoyEuvKyNyKfwQvDVmp2cRwVG6bXE77ti/f7T2O59lDdeB+CAmO2zM7uN3DW6vRwxg19MiKul3zG+/06lRkuVF9EiZD05rmdkViR5hxTBRRapJo9jjMwZ5XReMF6Rw4h8COw0ShNy6udQrd/aozSpzvcABsxTWvE83vD3BtxwCZsIewkW7Qp+oTasESWU3QpGd+JhSMZGJWb9vYgJS0odkjwLTbQ3O9YOwzBls4DEep/GkRC+V8JoDQdfg/u//nDYmzVdrWaPhwYZzTjh25UjmXPfPaRlH0WLoZqs7QPtr0HFElVntyFLwi7wcO9+XFWWkeZujjl08bjlJyeXcNg2InU6gtOKaCVMW0M1wZ7GvjjiBdQoH3cX11amC93NAQPcleLVkggI7z+2a6pqlP0jnaL0LG8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
